directories:
  data: data
  tmp: data/tmp

corpora:
  - id: lirical
    custom_variants:
      - id: no_phenotype

configs:
  - tool: template
    id: template-1.0.0
    version: 1.0.0

runs:
  - tool: template
    corpus: lirical
    corpusvariant: default
    version: 1.0.0
    configuration: template-1.0.0