directories:
  data: data
  tmp: data/tmp

corpora:
  - id: lirical
    custom_variants:
      - id: no_phenotype

semsim:
  profiles:
    - subset: hp-mp
      method: semsimian
      ontology: phenio-monarch
      threshold: 0.4
      prefixes:
        subject: hp
        object: mp

mappings:
  - id: hp
  - id: mp
  - id: zp
ontologies:
  - id: phenio-monarch
    mirror_from: http://purl.obolibrary.org/obo/upheno.owl

configs:
  - tool: exomiser
    id: exomiser-13.3.0
    version: 13.3.0
    phenotype: 2309
  # - tool: exomiser
  #   id: exomiser-13.3.0
  #   version: 13.3.0
  #   phenotype: 2309
  # - tool: exomiser
  #   id: exomiser-14.0.0
  #   version: 14.0.0
  #   phenotype: 2402
  # - tool: exomiser
  #   id: exomiser-phenio-all-ingest-13.3.0
  #   preprocessing:
  #     - phenio-monarch-hp-hp.0.4.semsimian.sql
  #     - phenio-monarch-hp-mp.0.4.semsimian.sql
  #     - phenio-monarch-hp-zp.0.4.semsimian.sql
  #   version: 13.3.0
  #   phenotype: 2309
  # - tool: gado
  #   id: gado-1.0.1
  #   version: 1.0.1
  # - tool: phen2gene
  #   id: phen2gene-1.2.3
  #   version: 1.2.3

runs:
  - tool: exomiser
    corpus: lirical
    corpusvariant: small_version
    version: 13.3.0
    configuration: exomiser-13.3.0
  # - tool: exomiser
  #   corpus: lirical
  #   corpusvariant: default
  #   version: 13.3.0
  #   configuration: exomiser-13.3.0
  # - tool: exomiser
  #   corpus: lirical
  #   corpusvariant: default
  #   version: 14.0.0
  #   configuration: exomiser-14.0.0
  # - tool: exomiser
  #   corpus: lirical
  #   corpusvariant: default
  #   version: 13.3.0
  #   configuration: exomiser-phenio-all-ingest-13.3.0
  # - tool: phen2gene
  #   corpus: lirical
  #   corpusvariant: default
  #   version: 1.2.3
  #   configuration: phen2gene-1.2.3
  # - tool: gado
  #   corpus: lirical
  #   corpusvariant: default
  #   version: 1.0.1
  #   configuration: gado-1.0.1
