directories:
  data: data
  tmp: data/tmp

corpora:
  - id: lirical
    custom_variants:
      - id: no_phenotype

mappings:
  - id: hp
  - id: mp
  - id: zp
ontologies:
  - id: phenio-monarch
    mirror_from: http://purl.obolibrary.org/obo/upheno.owl

configs:
  - tool: exomiser
    id: default-13.3.0
    version: 13.3.0
    phenotype: 2309
  - tool: exomiser
    id: default-14.0.0
    version: 14.0.0
    phenotype: 2402
  - tool: gado
    id: default-1.0.1
    version: 1.0.1
  - tool: phen2gene
    id: default-1.2.3
    version: 1.2.3

runs:
  - tool: exomiser
    corpus: lirical
    corpusvariant: default
    version: 13.3.0
    configuration: default-13.3.0
  - tool: exomiser
    corpus: lirical
    corpusvariant: default
    version: 14.0.0
    configuration: default-14.0.0
  - tool: phen2gene
    corpus: lirical
    corpusvariant: default
    version: 1.2.3
    configuration: default-1.2.3
  - tool: gado
    corpus: lirical
    corpusvariant: default
    version: 1.0.1
    configuration: default-1.0.1
