phenotype:
  version: 2309
  url: https://data.monarchinitiative.org/exomiser/latest/

directories:
  data: data
  tmp: data/tmp

corpora:
  - id: lirical
    scrambled:
      - factor: 0
      - factor: 0.5
      - factor: 0.7
    custom_variants:
      - id: no_phenotype

configs:
  - tool: exomiser
    version: 13.1.0
    configuration: 2309_phenotype

runs:
  - tool: exomiser
    corpus: lirical
    corpusvariant: scrambled-0
    version: 13.1.0
    configuration: 2309_phenotype
  - tool: exomiser
    corpus: lirical
    corpusvariant: scrambled-0.5
    version: 13.1.0
    configuration: 2309_phenotype
  - tool: exomiser
    corpus: lirical
    corpusvariant: scrambled-0.7
    version: 13.1.0
    configuration: 2309_phenotype
