directories:
  data: data
  tmp: data/tmp

corpora:
  - id: lirical
    variant: default
    custom_variants:
      - id: no_phenotype
  - id: lirical
    variant: small_version
    custom_variants:
      - id: no_phenotype
  - id: phenopacket-store
    variant: default
    custom_variants:
      - id: no_phenotype

configs:
  - name: Default configuration for Exomiser 13
    tool: exomiser
    id: exomiser-13.3.0
    version: 13.3.0
    phenotype: 2309
  - name: Default configuration for Exomiser 14
    tool: exomiser
    id: exomiser-14.0.0
    version: 14.0.0
    phenotype: 2402
  - name: S01 - Exomiser 13 with semantic similarity profiles (PHENIO Monarch), 0.4 threshold
    tool: exomiser
    id: S01
    # TODO: Change to latest Exomiser version for all!
    version: 13.3.0
    phenotype: 2309
    preprocessing:
      - phenio-monarch-hp-hp.0.4.semsimian.sql
      - phenio-monarch-hp-mp.0.4.semsimian.sql
      - phenio-monarch-hp-zp.0.4.semsimian.sql
  - name: S02 - Exomiser 13 with semantic similarity profiles (PHENIO Equivalent), 0.4 threshold
    tool: exomiser
    id: S02
    version: 13.3.0
    phenotype: 2309
    preprocessing:
      - phenio-equivalent-hp-hp.0.4.semsimian.sql
      - phenio-equivalent-hp-mp.0.4.semsimian.sql
      - phenio-equivalent-hp-zp.0.4.semsimian.sql
  - name: S03 - Exomiser 13 with semantic similarity profiles (PHENIO Flat), 0.4 threshold
    tool: exomiser
    id: S03
    version: 13.3.0
    phenotype: 2309
    preprocessing:
      - phenio-flat-hp-hp.0.4.semsimian.sql
      - phenio-flat-hp-mp.0.4.semsimian.sql
      - phenio-flat-hp-zp.0.4.semsimian.sql
  - name: S04 - Exomiser 13 with semantic similarity profiles (PHENIO Release), 0.4 threshold
    tool: exomiser
    id: S04
    version: 13.3.0
    phenotype: 2309
    preprocessing:
      - phenio-release-hp-hp.0.4.semsimian.sql
      - phenio-release-hp-mp.0.4.semsimian.sql
      - phenio-release-hp-zp.0.4.semsimian.sql
  - name: C01 - Exomiser 13 with semantic similarity profiles (PHENIO Monarch), 0.4 threshold, only HP
    tool: exomiser
    id: C01
    version: 13.3.0
    phenotype: 2309
    preprocessing:
      - phenio-monarch-hp-hp.0.4.semsimian.sql
      - phenio-monarch-hp-mp-truncate.sql
      - phenio-monarch-hp-zp-truncate.sql
  - name: C02 - Exomiser 13 with semantic similarity profiles (PHENIO Monarch), 0.4 threshold, only HP, MP
    tool: exomiser
    id: C02
    version: 13.3.0
    phenotype: 2309
    preprocessing:
      - phenio-monarch-hp-hp.0.4.semsimian.sql
      - phenio-monarch-hp-mp.0.4.semsimian.sql
      - phenio-monarch-hp-zp-truncate.sql
  - name: C05 - Exomiser 13 with semantic similarity profiles (PHENIO Monarch), 0.4 threshold, only HP, ZP
    tool: exomiser
    id: C05
    version: 13.3.0
    phenotype: 2309
    preprocessing:
      - phenio-monarch-hp-hp.0.4.semsimian.sql
      - phenio-monarch-hp-mp-truncate.sql
      - phenio-monarch-hp-zp.0.4.semsimian.sql
  - name: I01 - Exomiser 13 with semantic similarity profiles (PHENIO Monarch), 0.7 threshold
    tool: exomiser
    id: I01
    # TODO: Change to latest Exomiser version for all!
    version: 13.3.0
    phenotype: 2309
    preprocessing:
      - phenio-monarch-hp-hp.0.7.semsimian.sql
      - phenio-monarch-hp-mp.0.7.semsimian.sql
      - phenio-monarch-hp-zp.0.7.semsimian.sql
  - name: I02 - Exomiser 13 with semantic similarity profiles (PHENIO Monarch), 0.4 threshold, IC scores
    tool: exomiser
    id: I02
    # TODO: Change to latest Exomiser version for all!
    version: 13.3.0
    phenotype: 2309
    preprocessing:
      - phenio-monarch-hp-hp.0.4.semsimian.ic.sql
      - phenio-monarch-hp-mp.0.4.semsimian.ic.sql
      - phenio-monarch-hp-zp.0.4.semsimian.ic.sql


## VINI ADD C4!

## Future Nico: Consider that version number in "runs" is redundant, as it is already in the "configs" section. Maybe remove it from "runs" and add a "config" field to each run.
## I think you can use caching and maps to get the version from the config

runs:
  - name: Default configuration for Exomiser 13 on LIRICAL Corpus
    tool: exomiser
    corpus: lirical
    corpusvariant: default
    version: 13.3.0
    configuration: exomiser-13.3.0
  - name: Default configuration for Exomiser 14 on LIRICAL Corpus
    tool: exomiser
    corpus: lirical
    corpusvariant: default
    version: 14.0.0
    configuration: exomiser-14.0.0
  - name: C01 on LIRICAL Corpus
    tool: exomiser
    corpus: lirical
    corpusvariant: default
    version: 13.3.0
    configuration: C01
  - name: C02 on LIRICAL Corpus
    tool: exomiser
    corpus: lirical
    corpusvariant: default
    version: 13.3.0
    configuration: C02
  - name: C05 on LIRICAL Corpus
    tool: exomiser
    corpus: lirical
    corpusvariant: default
    version: 13.3.0
    configuration: C05
  - name: S01 on LIRICAL Corpus
    tool: exomiser
    corpus: lirical
    corpusvariant: default
    version: 13.3.0
    configuration: S01
  - name: S02 on LIRICAL Corpus
    tool: exomiser
    corpus: lirical
    corpusvariant: default
    version: 13.3.0
    configuration: S02
  - name: S03 on LIRICAL Corpus
    tool: exomiser
    corpus: lirical
    corpusvariant: default
    version: 13.3.0
    configuration: S03
  - name: S04 on LIRICAL Corpus
    tool: exomiser
    corpus: lirical
    corpusvariant: default
    version: 13.3.0
    configuration: S04
  - name: I01 on LIRICAL Corpus
    tool: exomiser
    corpus: lirical
    corpusvariant: default
    version: 13.3.0
    configuration: I01
  - name: I02 on LIRICAL Corpus
    tool: exomiser
    corpus: lirical
    corpusvariant: default
    version: 13.3.0
    configuration: I02



##### PHENOPACKETS STORE


  - name: Default configuration for Exomiser 13 on Phenopacket Store Corpus
    tool: exomiser
    corpus: phenopacket-store
    corpusvariant: default
    version: 13.3.0
    configuration: exomiser-13.3.0
  - name: Default configuration for Exomiser 14 on Phenopacket Store Corpus
    tool: exomiser
    corpus: phenopacket-store
    corpusvariant: default
    version: 14.0.0
    configuration: exomiser-14.0.0
  - name: C01 on Phenopacket Store Corpus
    tool: exomiser
    corpus: phenopacket-store
    corpusvariant: default
    version: 13.3.0
    configuration: C01
  - name: C02 on Phenopacket Store Corpus
    tool: exomiser
    corpus: phenopacket-store
    corpusvariant: default
    version: 13.3.0
    configuration: C02
  - name: C05 on Phenopacket Store Corpus
    tool: exomiser
    corpus: phenopacket-store
    corpusvariant: default
    version: 13.3.0
    configuration: C05
  - name: S01 on Phenopacket Store Corpus
    tool: exomiser
    corpus: phenopacket-store
    corpusvariant: default
    version: 13.3.0
    configuration: S01
  - name: S02 on Phenopacket Store Corpus
    tool: exomiser
    corpus: phenopacket-store
    corpusvariant: default
    version: 13.3.0
    configuration: S02
  - name: S03 on Phenopacket Store Corpus
    tool: exomiser
    corpus: phenopacket-store
    corpusvariant: default
    version: 13.3.0
    configuration: S03
  - name: S04 on Phenopacket Store Corpus
    tool: exomiser
    corpus: phenopacket-store
    corpusvariant: default
    version: 13.3.0
    configuration: S04
  - name: I01 on Phenopacket Store Corpus
    tool: exomiser
    corpus: lirical
    corpusvariant: default
    version: 13.3.0
    configuration: I01
  - name: I02 on Phenopacket Store Corpus
    tool: exomiser
    corpus: lirical
    corpusvariant: default
    version: 13.3.0
    configuration: I02
