directories:
  data: data
  tmp: data/tmp

corpora:
  - id: lirical
    custom_variants:
      - id: no_phenotype

semsim:
  mappings:
    - id: hp
    - id: mp
    - id: zp
  ontologies:
    - id: phenio-monarch
      mirror_from: http://purl.obolibrary.org/obo/upheno.owl
  profiles:
    - subset: hp-hp
      method: semsimian
      ontology: phenio-monarch
      threshold: 0.4
      prefixes:
        subject: hp
        object: hp
    - subset: hp-mp
      method: semsimian
      ontology: phenio-monarch
      threshold: 0.4
      prefixes:
        subject: hp
        object: mp
    - subset: hp-zp
      method: semsimian
      ontology: phenio-monarch
      threshold: 0.4
      prefixes:
        subject: hp
        object: zp

# corpora:
#   - id: lirical
#     scrambled:
#       - factor: 0
#       - factor: 0.5
#       - factor: 0.7
#     custom_variants:
#       - id: no_phenotype

configs:
  - tool: exomiser
    version: 13.2.1
    phenotype: 2302
    configuration: 2302_phenotype
  - tool: exomiser
    version: 13.3.0
    phenotype: 2302
    configuration: 2302_phenotype
  - tool: exomiser
    version: 13.2.1
    phenotype: 2309
    configuration: 2309_phenotype
  - tool: exomiser
    version: 13.3.0
    phenotype: 2309
    configuration: 2309_phenotype

runs:
  - tool: exomiser
    corpus: lirical
    corpusvariant: default
    version: 13.2.1
    configuration: 2302_phenotype
  - tool: exomiser
    corpus: lirical
    corpusvariant: default
    version: 13.3.0
    configuration: 2302_phenotype
  - tool: exomiser
    corpus: lirical
    corpusvariant: default
    version: 13.2.1
    configuration: 2309_phenotype
  - tool: exomiser
    corpus: lirical
    corpusvariant: default
    version: 13.3.0
    configuration: 2309_phenotype
  - tool: exomiser
    corpus: lirical
    corpusvariant: default
    version: 13.2.1
    configuration: 2309_phenotype-hp-mp
  - tool: exomiser
    corpus: lirical
    corpusvariant: default
    version: 13.3.0
    configuration: 2309_phenotype-hp-hp
  - tool: exomiser
    corpus: lirical
    corpusvariant: default
    version: 13.3.0
    configuration: 2309_phenotype-hp-mp
  - tool: exomiser
    corpus: lirical
    corpusvariant: default
    version: 13.3.0
    configuration: 2309_phenotype-hp-zp
