directories:
  data: data
  tmp: data/tmp

configs:
  - tool: exomiser
    id: exomiser-13.3.0
    version: 13.3.0
    phenotype: 2309
      
runs:
  - tool: exomiser
    corpus: lirical
    corpusvariant: small_version
    version: 13.3.0
    configuration: exomiser-13.3.0
