tool: phen2gene
tool_version: 1.2.3
variant_analysis: False
gene_analysis: True
disease_analysis: False
tool_specific_configuration_options:
  environment: local
  phen2gene_python_executable: ../../runners/Phen2Gene/phen2gene.py
  post_process:
    score_order: descending
